server:
  port: 8080
  
spring:
  application:
    name: gateway-mx1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
    register-with-eureka: true
    fetch-registry: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enable: false
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 30000
zuul:
  retryable: true
  
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: ON

